== Introduction

Based on the open source Istio project, Red Hat OpenShift Service Mesh adds a transparent layer on existing distributed applications without requiring any changes to the service code.
You add Red Hat OpenShift Service Mesh support to services by deploying a special sidecar proxy to relevant services in the mesh that intercepts all network communication between microservices.
You configure and manage the Service Mesh using the Service Mesh control plane features.
To learn more about the OpenShift Service Mesh, review the https://docs.openshift.com/rosa/service_mesh/v2x/ossm-about.html[OpenShift documentation].

:numbered:
== Deploy Control Plane

. First, let's create a project (namespace) for us to deploy the service mesh control plane into.
To do so, run the following command:
+
[source,sh,role=execute]
----
oc new-project istio-system
----
+
.Sample Output
[source,text,options=nowrap]
----
Now using project "istio-system" on server "https://api.rosa-6n4s8.1c1c.p1.openshiftapps.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.io/e2e-test-images/agnhost:2.33 -- /agnhost serve-hostname
----

. Next, let's deploy the service mesh control plane.
To do so, run the following command:
+
[source,sh,role=execute]
----
cat << EOF | oc apply -f -
---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.6
  security:
    identity:
      type: ThirdParty
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
EOF
----
+
.Sample Output
[source,text,options=nowrap]
----
servicemeshcontrolplane.maistra.io/basic created
----
+
[WARNING]
====
If you receive an error that is similar to the below error, ensure your operators have finished installing and try again:

[source,texinfo]
----
Internal error occurred: failed calling webhook "smcp.mutation.maistra.io": failed to call webhook: Post "https://maistra-admission-controller.openshift-operators.svc:443/mutate-smcp?timeout=10s": dial tcp 10.128.2.63:11999: connect: connection refused
----
====

. Next, let's watch the progress of the service mesh control plane rollout.
To do so, run run the following command:
+
[source,sh,role=execute]
----
watch oc get pods -n istio-system
----
+
.Sample Output
[source,text,options=nowrap]
----
Every 2.0s: oc get pods -n istio-system                  bastion.94rr7.internal: Wed Mar 12 16:05:27 2025

NAME                                    READY   STATUS    RESTARTS   AGE
grafana-65595d4c5c-d2b5m                2/2     Running   0          62s
istio-egressgateway-686db4fbcd-bthzc    1/1     Running   0          62s
istio-ingressgateway-866997b9d5-64p87   1/1     Running   0          62s
istiod-basic-59c69d6d65-ff7tt           1/1     Running   0          102s
jaeger-5994c96f-gbwm4                   2/2     Running   0          61s
kiali-cc9dfdc56-zbwvj                   0/1     Running   0          14s
prometheus-5d89c758f8-qnhrx             3/3     Running   0          93s
----
+
Once all the pods are running (like in the example above), hit kbd:[CTRL+c] and proceed to the next step.

. Next, let's verify that the service mesh control plane is successfully installed.
To do so, run the following command:
+
[source,sh,role=execute]
----
oc -n istio-system get smcp
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME    READY   STATUS            PROFILES      VERSION   AGE
basic   9/9     ComponentsReady   ["default"]   2.6.6     90s
----
+
The installation has finished successfully when the STATUS column says `ComponentsReady`.

*Congratulations!*

You've successfully deployed the OpenShift Service Mesh control plane to your cluster.
