== Introduction

It's time for us to put our cluster to work and deploy a workload! We're going to deploy an example Node.js application, https://github.com/rhpds/microsweeper-rosa[microsweeper].

This lab demonstrates how ROSA (an AWS native service) can easily and securely run applications.

:numbered:
== Create an OpenShift Project

. First, let's create a project (also known as namespace). A project is a unit of organization within OpenShift that provides isolation for applications and resources. To do so, run the following command:
+
[source,sh,role=execute]
----
oc new-project microsweeper-ex
----
+
.Sample Output
[source,text,options=nowrap]
----
Now using project "microsweeper-ex" on server "https://api.rosa-6n4s8.1c1c.p1.openshiftapps.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.io/e2e-test-images/agnhost:2.33 -- /agnhost serve-hostname
----

== Deploy the Microsweeper app

The example application that we use is a Node.js application. You can find the source code for the application at https://github.com/rhpds/microsweeper-rosa. But for the purposes of this experience you will be deploying a pre-built container image.

. First, create a service account to use for the application. It is usually a good idea to run each application with its own service account in order to manage permissions.
To do so, run the following command:
+
[source,sh,role=execute]
----
oc -n microsweeper-ex create serviceaccount microsweeper
----
+
.Sample Output
[source,text,options=nowrap]
----
serviceaccount/microsweeper created
----

. Create the *microsweeper-appservice* `Deployment`:
+
[source,sh,role=execute]
----
cat <<EOF | oc apply -f -
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsweeper-appservice
  namespace: microsweeper-ex
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: microsweeper-appservice
      app.kubernetes.io/name: microsweeper-appservice
  template:
    metadata:
      labels:
        deployment: microsweeper-appservice
        app.kubernetes.io/name: microsweeper-appservice
    spec:
      serviceAccountName: microsweeper
      containers:
      - name: microsweeper-appservice
        image: quay.io/rhpds/microsweeper-appservice:rosa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
EOF
----
+
.Sample Output
[source,texinfo]
----
deployment.apps/microsweeper-appservice created
----
+
[TIP]
====
The application is configured using the service account name.

* `serviceAccountName: microsweeper` tells OpenShift to use the service account that you configured previously to run this pod.
====

. Now that your application is running we need to make the application accessible outside of your OpenShift cluster so that you can test it.
+
Create the `Service` for the application:
+
[source,sh,role=execute]
----
oc -n microsweeper-ex expose deployment microsweeper-appservice
----
+
.Sample Output
[source,texinfo]
----
service/microsweeper-appservice exposed
----

. And finally create a `Route` that publishes this application. This particular route will have TLS encryption (`edge`) and redirect `http` requests to `https` (`Redirect)`.
+
[source,sh,role=execute]
----
oc -n microsweeper-ex create route edge --service=microsweeper-appservice --insecure-policy=Redirect
----
+
.Sample Output
[source,texinfo]
----
route.route.openshift.io/microsweeper-appservice created
----

=== Test the application

. Get the the URL for your application route:

[source,sh,role=execute]
----
echo "https://$(oc -n microsweeper-ex get route microsweeper-appservice -o jsonpath='{.spec.host}')"
----
+
.Sample Output
[source,text,options=nowrap]
----
https://microsweeper-appservice-microsweeper-ex.apps.rosa-6n4s8.1c1c.p1.openshiftapps.com
----

. Use the returned URL to open the Microsweeper application in a web browser of your choice.
+
You should be able to play a few games.

=== Application IP

Let's take a quick look at what IP the application resolves to.

Back in your terminal, run the following command:

[source,sh,role=execute]
----
nslookup $(oc -n microsweeper-ex get route microsweeper-appservice -o jsonpath='{.spec.host}')
----

.Sample Output
[source,text,options=nowrap]
----
Server:         192.168.0.2
Address:        192.168.0.2#53

Non-authoritative answer:
Name:   microsweeper-appservice-microsweeper-ex.apps.rosa.rosa-7v44k.u7g2.p3.openshiftapps.com
Address: 3.21.3.12
----

Notice the IP address;
can you guess where it comes from?

It comes from the ROSA Load Balancer.
In this workshop, we are using a public cluster which means the load balancer is exposed to the Internet.
If this was a private cluster, you would have to have connectivity to the VPC ROSA is running on.
This could be via a VPN connection, AWS DirectConnect, or something else.

== Summary

Here you learned:

* Create an OpenShift project
* Build a Node.js application from a Git repository.
* Expose the Microsweeper application
* Access the publicly exposed Microsweeper app using OpenShift routes
