== Explore your ROSA environment

As you have seen in the video your ROSA cluster has already been deployed for you. This is both to speed things up for this lab and because your AWS user does not have sufficient permissions to deploy a new ROSA cluster - only enough to follow these lab instructions.

All interactions with ROSA happen through the `rosa` CLI (or on the Red Hat Console web page - to which you also do not have access). So let's use the CLI to explore what you have.

Rosa deploy: {rosa_deploy_hcp}

. List all deployed ROSA clusters in the AWS account:
+
[source,sh,role=execute]
----
rosa list clusters
----
+
ifeval::["{rosa_deploy_hcp}" == "True"]
.Sample Output
[source,texinfo,options=nowrap,subs="attributes"]
----
ID                                NAME        STATE  TOPOLOGY
26rb36mq3avdbitdo3qv3t7sc7s4ui16  rosa-{guid}  ready  Hosted CP
----
endif::[]
ifeval::["{rosa_deploy_hcp}" == "False"]
.Sample Output
[source,texinfo,options=nowrap,subs=attributes]
----
ID                                NAME        STATE  TOPOLOGY
26rate9v2s9k7mjgtag8gcoh3kkdl6qj  rosa-{guid}  ready  Classic (STS)
----
endif::[]
+
[TIP]
====
The ID of your cluster will be different than in the sample output above.

Also notice the Topology and state. State should be *ready* and Topology could be either *Classic (STS)* or *Hosted CP* which stands for Hosted Control Plane - a new, resource saving way of deploying a ROSA cluster.
====

. Now let's examine this cluster a bit more by describing the cluster (the `$GUID` environment variable is already set for you so you can immediately describe your individual cluster):
+
[source,sh,role=execute]
----
rosa describe cluster --cluster rosa-$GUID
----
+
ifeval::["{rosa_deploy_hcp}" == "False"]
.Sample Output
[source,texinfo,subs="attributes"]
----
Name:                       rosa-{guid}
ID:                         26rate9v2s9k7mjgtag8gcoh3kkdl6qj
External ID:                ef03828c-43bb-4e49-b8fc-20f0be436154
Control Plane:              Customer Hosted
OpenShift Version:          4.12.36
Channel Group:              stable
DNS:                        rosa-{guid}.z6qe.p1.openshiftapps.com
AWS Account:                698064993456
API URL:                    {rosa_api_url}
Console URL:                {rosa_console_url}
Region:                     us-east-2
Multi-AZ:                   false
Nodes:
 - Control plane:           3
 - Infra:                   2
 - Compute:                 2
   - Root disk size:        300 GiB
Network:
 - Type:                    OVNKubernetes
 - Service CIDR:            172.30.0.0/16
 - Machine CIDR:            10.0.0.0/16
 - Pod CIDR:                10.128.0.0/14
 - Host Prefix:             /23
Workload Monitoring:        Enabled
Infra ID:                   rosa-{guid}-dw6cz
Ec2 Metadata Http Tokens:   optional
STS Role ARN:               arn:aws:iam::698064993456:role/ManagedOpenShift-Installer-Role
Support Role ARN:           arn:aws:iam::698064993456:role/ManagedOpenShift-Support-Role
Instance IAM Roles:
 - Control plane:           arn:aws:iam::698064993456:role/ManagedOpenShift-ControlPlane-Role
 - Worker:                  arn:aws:iam::698064993456:role/ManagedOpenShift-Worker-Role
Operator IAM Roles:
 - arn:aws:iam::698064993456:role/rosa-{guid}-r8e0-openshift-cloud-network-config-controller-cloud-
 - arn:aws:iam::698064993456:role/rosa-{guid}-r8e0-openshift-machine-api-aws-cloud-credentials
 - arn:aws:iam::698064993456:role/rosa-{guid}-r8e0-openshift-cloud-credential-operator-cloud-creden
 - arn:aws:iam::698064993456:role/rosa-{guid}-r8e0-openshift-image-registry-installer-cloud-credent
 - arn:aws:iam::698064993456:role/rosa-{guid}-r8e0-openshift-ingress-operator-cloud-credentials
 - arn:aws:iam::698064993456:role/rosa-{guid}-r8e0-openshift-cluster-csi-drivers-ebs-cloud-credenti
Managed Policies:           No
State:                      ready 
Private:                    No
Created:                    Oct 13 2023 08:15:57 UTC
Details Page:               https://console.redhat.com/openshift/details/s/2WhVmXVt37Zln8gcdLq3eadaYeS
OIDC Endpoint URL:          https://rh-oidc.s3.us-east-1.amazonaws.com/26rate9v2s9k7mjgtag8gcoh3kkdl6qj (Classic)
----
endif::[]
ifeval::["{rosa_deploy_hcp}" == "True"]
.Sample Output
[source,texinfo,subs="attributes"]
----
Name:                       rosa-{guid}
ID:                         26rb36mq3avdbitdo3qv3t7sc7s4ui16
External ID:                1f4e7022-6556-4529-af7d-b3b470091990
Control Plane:              ROSA Service Hosted
OpenShift Version:          4.12.36
Channel Group:              stable
DNS:                        rosa-{guid}.8ffn.p3.openshiftapps.com
AWS Account:                237325068408
API URL:                    {rosa_api_url}
Console URL:                {rosa_console_url}
Region:                     us-east-2
Availability:
 - Control Plane:           MultiAZ
 - Data Plane:              SingleAZ
Nodes:
 - Compute (desired):       2
 - Compute (current):       2
Network:
 - Type:                    OVNKubernetes
 - Service CIDR:            172.30.0.0/16
 - Machine CIDR:            10.0.0.0/16
 - Pod CIDR:                10.128.0.0/14
 - Host Prefix:             /23
Workload Monitoring:        Enabled
Ec2 Metadata Http Tokens:   optional
STS Role ARN:               arn:aws:iam::237325068408:role/ManagedOpenShift-HCP-ROSA-Installer-Role
Support Role ARN:           arn:aws:iam::237325068408:role/ManagedOpenShift-HCP-ROSA-Support-Role
Instance IAM Roles:
 - Worker:                  arn:aws:iam::237325068408:role/ManagedOpenShift-HCP-ROSA-Worker-Role
Operator IAM Roles:
 - arn:aws:iam::237325068408:role/rosa-{guid}-kube-system-kube-controller-manager
 - arn:aws:iam::237325068408:role/rosa-{guid}-kube-system-capa-controller-manager
 - arn:aws:iam::237325068408:role/rosa-{guid}-kube-system-control-plane-operator
 - arn:aws:iam::237325068408:role/rosa-{guid}-kube-system-kms-provider
 - arn:aws:iam::237325068408:role/rosa-{guid}-openshift-image-registry-installer-cloud-credentials
 - arn:aws:iam::237325068408:role/rosa-{guid}-openshift-ingress-operator-cloud-credentials
 - arn:aws:iam::237325068408:role/rosa-{guid}-openshift-cluster-csi-drivers-ebs-cloud-credentials
 - arn:aws:iam::237325068408:role/rosa-{guid}-openshift-cloud-network-config-controller-cloud-crede
Managed Policies:           Yes
State:                      ready 
Private:                    No
Created:                    Oct 13 2023 08:28:11 UTC
Details Page:               https://console.redhat.com/openshift/details/s/2WhXGgLtboCE2fadfRDSoGtt44H
OIDC Endpoint URL:          https://rh-oidc.s3.us-east-1.amazonaws.com/26rb33og2cncnmb2t98q90jf9fr359nb (Managed)
Audit Log Forwarding:       disabled
----
endif::[]
+
Note that not all values in the sample output will match exactly your environment.

. Get the API URL for your cluster:
+
[source,sh,role=execute]
----
rosa describe cluster --cluster rosa-$GUID --output json | jq -r .api.url
----
+
.Sample Output
[source,texinfo,subs="attributes"]
----
{rosa_api_url}
----

. Get the OpenShift Console URL for your cluster:
+
[source,sh,role=execute]
----
rosa describe cluster --cluster rosa-$GUID --output json | jq -r .console.url
----
+
.Sample Output
[source,texinfo,subs="attributes"]
----
{rosa_console_url}
----

. A temporary admin user has already been created for you on the ROSA OpenShift cluster.
+
[subs="attributes"]
====
* *Admin user ID:* {rosa_admin_user}
* *Admin user Password:* {rosa_admin_password}
====

. Now that you have the information about the Admin credentials and the API URL for your cluster you can log into your cluster:
cmdo
+
[source,sh,role=execute,subs="attributes"]
----
oc login --username {rosa_admin_user} --password {rosa_admin_password} {rosa_api_url}
----
+
ifeval::["{rosa_deploy_hcp}" == "True"]
.Sample Output
[source,texinfo,options=nowrap]
----
Login successful.

You have access to 75 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
Welcome! See 'oc help' to get started.
----
endif::[]
ifeval::["{rosa_deploy_hcp}" == "False"]
.Sample Output
[source,texinfo,options=nowrap]
----
Login successful.

You have access to 100 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
Welcome! See 'oc help' to get started.
----
endif::[]

. To check that you are logged in as the admin user you can run `oc whoami`:
+
[source,sh,role=execute]
----
oc whoami
----
+
.Sample Output
[source,texinfo,options=nowrap,subs="attributes"]
----
{rosa_admin_user}
----

. You can now use the cluster as an admin user, which will suffice for this workshop. Though, for any other use, it is highly recommended to set up an IdP.

=== Login to the OpenShift Web Console

Next, let's log in to the OpenShift Web Console. Remember that you used the `rosa` command before to retrieve the console URL.

However once you are logged into the cluster you can also use the OpenShift command to find out the console URL.

. Grab your cluster's web console URL. To do so, run the following command:
+
[source,sh,role=execute]
----
oc whoami --show-console
----
+
.Sample Output
[source,text,options=nowrap,subs="attributes"]
----
{rosa_console_url}
----

. Next, open the printed URL in a web browser.
. Enter the username (`{rosa_admin_user}`) and password from the previous section (`{rosa_admin_password}`.

If you don't see an error, congratulations! You're now logged into the cluster and ready to move on to the workshop content.
